name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '313.0.0'
          project_id: $GOOGLE_PROJECT_ID
          service_account_key: $GOOGLE_SERVICE_ACCOUNT_FILE

      - name: Authenticate Docker to Google Cloud
        run: gcloud auth configure-docker -q

      - name: Build and Deploy
        run: gcloud builds submit --config=cloudbuild.yaml .
