on:
  push:
    branches:
      - main
name: Deploying to Cloud Store

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          cache: true

      - name: Maven build
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to google cloud
        run: |
          gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
          gcloud app deploy app.yaml --quiet --project $GOOGLE_PROJECT_ID
